### ISSUE TITLE
Are JSON Array Data Types Supported In Cubicle? 

### ISSUE THREAD

**Issue by johnnygoodman** [PlasticLizard/Cubicle#4]
Howdy,

JSON Schema and Cubicle Defs: http://gist.github.com/558619

Calling It: http://gist.github.com/558621

Result: [{"tags"=>nil}]

A definition like this works as expected: http://gist.github.com/558628

Thanks!
Johnny

**Comment by PlasticLizard** [comment]
This should be better documented, but when using :expression=>'javascript' you have to use 'this.key' instead of just 'key' because the context the expression is evaluated in stores the document in the 'this' variable. When you use :field_name=>'my_field' cubicle adds the 'this' for you. You might also be able to get away with using :field_name=>'tags[0]' or :field_name=>'tags.first'

Please let me know if that works for you.

**Comment by PlasticLizard** [comment]
Here is an updated gist reflecting the change: http://gist.github.com/559554

**Comment by PlasticLizard** [comment]
Closing this
